// Copyright (c) 2013-2015 The btcsuite developers
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.

package electrum_test

import (
	"crypto/ecdsa"
	"crypto/elliptic"
	"crypto/tls"
	"crypto/x509"
	"encoding/pem"
	"testing"
	"time"

	electrum "github.com/btcsuite/btcd/electrum-server"
)

// TestNewTLSCertPair ensures the NewTLSCertPair function generates a loadable
// certificate pair on the P-256 curve.
func TestNewTLSCertPair(t *testing.T) {
	validUntil := time.Now().Add(10 * 365 * 24 * time.Hour)
	org := "test autogenerated cert"
	cert, key, err := electrum.NewTLSCertPair(org, validUntil, nil)
	if err != nil {
		t.Fatalf("failed with unexpected error: %v", err)
	}

	// Ensure the pair loads as a TLS certificate.
	if _, err := tls.X509KeyPair(cert, key); err != nil {
		t.Fatalf("failed to load the certificate pair: %v", err)
	}

	// Ensure the PEM-encoded cert that is returned can be decoded and
	// parsed into an X.509 certificate.
	pemCert, _ := pem.Decode(cert)
	if pemCert == nil {
		t.Fatalf("pem.Decode was unable to decode the certificate")
	}
	x509Cert, err := x509.ParseCertificate(pemCert.Bytes)
	if err != nil {
		t.Fatalf("failed with unexpected error: %v", err)
	}

	// Ensure the certificate uses the P-256 curve and a SHA-256 based
	// signature so every client TLS stack accepts it.
	pub, ok := x509Cert.PublicKey.(*ecdsa.PublicKey)
	if !ok {
		t.Fatalf("certificate public key is %T, not an ECDSA key",
			x509Cert.PublicKey)
	}
	if pub.Curve != elliptic.P256() {
		t.Fatalf("certificate curve is %s, want P-256",
			pub.Curve.Params().Name)
	}
	if x509Cert.SignatureAlgorithm != x509.ECDSAWithSHA256 {
		t.Fatalf("certificate signature algorithm is %s, want "+
			"ECDSA-SHA256", x509Cert.SignatureAlgorithm)
	}
}
