// Copyright (c) 2026 The btcsuite developers
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.

//go:build ignore

package main

import (
	"bytes"
	"fmt"
	"math/big"
	"os"
)

const outputFile = "ifma_cdf_generated.h"

func represented(limbs []*big.Int, bits uint) *big.Int {
	result := new(big.Int)
	for i, limb := range limbs {
		term := new(big.Int).Lsh(new(big.Int).Set(limb), bits*uint(i))
		result.Add(result, term)
	}
	return result
}

func asmLiteral(value *big.Int) string {
	if value.Sign() == 0 {
		return "0"
	}
	return fmt.Sprintf("0x%X", value.Uint64())
}

func main() {
	const limbBits = 52
	primeLimbs := []uint64{
		0xffffefffffc2f,
		0xfffffffffffff,
		0xfffffffffffff,
		0xfffffffffffff,
		0xffffffffffff,
	}

	constant := make([]*big.Int, 8)
	for i := range constant {
		constant[i] = new(big.Int)
	}
	for i, limb := range primeLimbs {
		constant[i].Lsh(new(big.Int).SetUint64(limb), 11)
	}
	constant[5].Lsh(big.NewInt(1), 46)

	// In base 2^52, 2^260 = 16*p + r52. The lane-five bias
	// therefore contributes 2^50*p after compensating for r52 in
	// the low limbs.
	compensation := new(big.Int).Mul(
		new(big.Int).Lsh(big.NewInt(1), 46),
		new(big.Int).SetUint64(0x1000003d10),
	)
	mask := new(big.Int).Sub(
		new(big.Int).Lsh(big.NewInt(1), limbBits),
		big.NewInt(1),
	)
	for i := 0; compensation.Sign() != 0; i++ {
		limb := new(big.Int).And(compensation, mask)
		constant[i].Sub(constant[i], limb)
		compensation.Rsh(compensation, limbBits)
	}

	prime := make([]*big.Int, len(primeLimbs))
	for i, limb := range primeLimbs {
		prime[i] = new(big.Int).SetUint64(limb)
	}
	wantFactor := new(big.Int).Add(
		new(big.Int).Lsh(big.NewInt(1), 50),
		big.NewInt(2048),
	)
	want := new(big.Int).Mul(represented(prime, limbBits), wantFactor)
	if got := represented(constant, limbBits); got.Cmp(want) != 0 {
		panic("ifmaCDF does not represent (2^50 + 2048) * p")
	}
	for _, limb := range constant {
		if !limb.IsUint64() {
			panic("ifmaCDF lane does not fit in 64 bits")
		}
	}

	var output bytes.Buffer
	fmt.Fprintln(&output, "// Copyright (c) 2026 The btcsuite developers")
	fmt.Fprintln(&output, "// Use of this source code is governed by an ISC")
	fmt.Fprintln(&output, "// license that can be found in the LICENSE file.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "// Code generated by gen_ifma_cdf.go; DO NOT EDIT.")
	fmt.Fprintln(&output)
	fmt.Fprintln(&output, "// Column combination constant for fused doubling.")
	for i, limb := range constant {
		fmt.Fprintf(&output, "DATA ifmaCDF<>+%d(SB)/8, $%s\n",
			i*8, asmLiteral(limb))
	}
	fmt.Fprintln(&output, "GLOBL ifmaCDF<>(SB), RODATA, $64")
	if err := os.WriteFile(outputFile, output.Bytes(), 0o644); err != nil {
		panic(err)
	}
}
