// Copyright (c) 2026 The btcsuite developers
// Use of this source code is governed by an ISC
// license that can be found in the LICENSE file.

// Code generated by gen_ifma_cdf.go; DO NOT EDIT.

// Column combination constant for fused doubling.
DATA ifmaCDF<>+0(SB)/8, $0x7FFBF7FFFFE17800
DATA ifmaCDF<>+8(SB)/8, $0x7FFFFFFFBFFFF70C
DATA ifmaCDF<>+16(SB)/8, $0x7FFFFFFFFFFFF800
DATA ifmaCDF<>+24(SB)/8, $0x7FFFFFFFFFFFF800
DATA ifmaCDF<>+32(SB)/8, $0x7FFFFFFFFFFF800
DATA ifmaCDF<>+40(SB)/8, $0x400000000000
DATA ifmaCDF<>+48(SB)/8, $0
DATA ifmaCDF<>+56(SB)/8, $0
GLOBL ifmaCDF<>(SB), RODATA, $64
