//go:build rpctest
// +build rpctest

package integration

import (
	"bufio"
	"bytes"
	"crypto/tls"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"net"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"
	"time"

	"github.com/btcsuite/btcd/blockchain"
	"github.com/btcsuite/btcd/btcjson"
	"github.com/btcsuite/btcd/btcutil/v2"
	"github.com/btcsuite/btcd/chaincfg/v2"
	"github.com/btcsuite/btcd/chainhash/v2"
	electrumclient "github.com/btcsuite/btcd/electrum-client"
	"github.com/btcsuite/btcd/integration/rpctest"
	"github.com/btcsuite/btcd/mempool"
	"github.com/btcsuite/btcd/txscript/v2"
	"github.com/btcsuite/btcd/wire/v2"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// electrumNotificationTimeout is how long the tests wait for a subscription
// notification from the electrum server before failing.
const electrumNotificationTimeout = 30 * time.Second

// freeListenAddr asks the kernel for a free localhost port and returns it as
// a listen address the electrum server under test can bind to.
func freeListenAddr(t *testing.T) string {
	t.Helper()

	l, err := net.Listen("tcp", "127.0.0.1:0")
	require.NoError(t, err)
	addr := l.Addr().String()
	require.NoError(t, l.Close())
	return addr
}

// electrumNode is a harness node with the electrum server enabled.
type electrumNode struct {
	*rpctest.Harness

	// tcpAddr and tlsAddr are the addresses of the plain TCP and the TLS
	// electrum listeners.
	tcpAddr string
	tlsAddr string

	// certPath is the certificate file the TLS electrum listener serves,
	// generated by the node on startup.
	certPath string
}

// newElectrumNode starts a harness node with the electrum server enabled.
func newElectrumNode(t *testing.T, createTestChain bool,
	numMatureOutputs uint32) *electrumNode {

	t.Helper()

	tcpAddr := freeListenAddr(t)
	tlsAddr := freeListenAddr(t)
	certPath := filepath.Join(t.TempDir(), "electrum.cert")
	keyPath := filepath.Join(filepath.Dir(certPath), "electrum.key")

	btcdCfg := []string{
		"--enableelectrum",
		"--electrumlisteners=" + tcpAddr,
		"--tlselectrumlisteners=" + tlsAddr,
		"--electrumcert=" + certPath,
		"--electrumkey=" + keyPath,
	}
	r, err := rpctest.New(&chaincfg.SimNetParams, nil, btcdCfg, "")
	require.NoError(t, err)
	require.NoError(t, r.SetUp(createTestChain, numMatureOutputs))
	t.Cleanup(func() {
		if err := r.TearDown(); err != nil {
			t.Logf("harness teardown: %v", err)
		}
	})

	// The node generates the electrum certificate pair on startup when the
	// files do not exist yet.
	require.FileExists(t, certPath)
	require.FileExists(t, keyPath)

	return &electrumNode{
		Harness:  r,
		tcpAddr:  tcpAddr,
		tlsAddr:  tlsAddr,
		certPath: certPath,
	}
}

// serializedHeaderHex returns the hex encoding of the serialized header.
func serializedHeaderHex(t *testing.T, header *wire.BlockHeader) string {
	t.Helper()

	var buf bytes.Buffer
	require.NoError(t, header.Serialize(&buf))
	return hex.EncodeToString(buf.Bytes())
}

// waitForHeaderTip returns the next chain tip notification.
func waitForHeaderTip(t *testing.T,
	ch <-chan electrumclient.HeaderTip) electrumclient.HeaderTip {

	t.Helper()

	select {
	case tip, ok := <-ch:
		require.True(t, ok, "header notification channel closed")
		return tip
	case <-time.After(electrumNotificationTimeout):
		t.Fatal("timed out waiting for a header notification")
		return electrumclient.HeaderTip{}
	}
}

// waitForStatus reads script hash status notifications until the expected
// status shows up, failing the test when it does not.
func waitForStatus(t *testing.T, ch <-chan string, expected string) {
	t.Helper()

	var seen []string
	for {
		select {
		case status, ok := <-ch:
			require.True(t, ok, "status notification channel closed")
			if status == expected {
				return
			}
			seen = append(seen, status)
		case <-time.After(electrumNotificationTimeout):
			t.Fatalf("timed out waiting for status %q, saw %q",
				expected, seen)
		}
	}
}

// verifyMerkleBranch folds the transaction hash with the merkle branch the
// server returned and requires that it arrives at the merkle root the block
// header commits to. The branch is ordered from the leaf level up and pos is
// the position of the transaction in the block.
func verifyMerkleBranch(t *testing.T, txHash *chainhash.Hash, branch []string,
	pos int, root *chainhash.Hash) {

	t.Helper()

	current := *txHash
	for _, hashStr := range branch {
		sibling, err := chainhash.NewHashFromStr(hashStr)
		require.NoError(t, err)

		if pos&1 == 1 {
			current = blockchain.HashMerkleBranches(sibling, &current)
		} else {
			current = blockchain.HashMerkleBranches(&current, sibling)
		}
		pos >>= 1
	}
	require.Equal(t, *root, current)
}

// TestElectrumServer spins up a node with the electrum server enabled and
// drives every method the server exposes with the electrum client, checking
// the responses against the node's RPC interface.
func TestElectrumServer(t *testing.T) {
	t.Parallel()

	node := newElectrumNode(t, true, 25)
	r, tcpAddr, tlsAddr := node.Harness, node.tcpAddr, node.tlsAddr

	client, err := electrumclient.Dial(tcpAddr)
	require.NoError(t, err)
	t.Cleanup(client.Close)

	// The server methods: version negotiation first, then the informational
	// methods.
	serverVersion, protocolVersion, err := client.ServerVersion(
		"btcd-integration-test", "1.4")
	require.NoError(t, err)
	require.NotEmpty(t, serverVersion)
	require.True(t, strings.HasPrefix(protocolVersion, "1.4"),
		"unexpected protocol version %q", protocolVersion)

	require.NoError(t, client.Ping())

	banner, err := client.ServerBanner()
	require.NoError(t, err)
	require.NotEmpty(t, banner)

	donationAddr, err := client.ServerDonationAddress()
	require.NoError(t, err)
	require.NotEmpty(t, donationAddr)

	features, err := client.ServerFeatures()
	require.NoError(t, err)
	require.Equal(t, chaincfg.SimNetParams.GenesisHash.String(),
		features.GenesisHash)
	require.Equal(t, "sha256", features.HashFunction)
	require.NotEmpty(t, features.ProtocolMin)
	require.NotEmpty(t, features.ProtocolMax)

	// Both listeners bind the same host so its entry must carry both ports.
	host, tcpPortStr, err := net.SplitHostPort(tcpAddr)
	require.NoError(t, err)
	tcpPort, err := strconv.Atoi(tcpPortStr)
	require.NoError(t, err)
	_, tlsPortStr, err := net.SplitHostPort(tlsAddr)
	require.NoError(t, err)
	tlsPort, err := strconv.Atoi(tlsPortStr)
	require.NoError(t, err)

	hostPorts, found := features.Hosts[host]
	require.True(t, found, "host %q missing from %v", host, features.Hosts)
	require.Equal(t, tcpPort, hostPorts.TCPPort)
	require.Equal(t, tlsPort, hostPorts.SSLPort)

	peers, err := client.ServerPeersSubscribe()
	require.NoError(t, err)
	require.Empty(t, peers)

	accepted, err := client.ServerAddPeer(nil)
	require.NoError(t, err)
	require.False(t, accepted)

	// The header methods, checked against the RPC interface.
	bestHash, bestHeight, err := r.Client.GetBestBlock()
	require.NoError(t, err)

	tip, tipCh, err := client.HeadersSubscribe()
	require.NoError(t, err)
	require.Equal(t, bestHeight, tip.Height)

	bestHeader, err := r.Client.GetBlockHeader(bestHash)
	require.NoError(t, err)
	require.Equal(t, serializedHeaderHex(t, bestHeader), tip.Hex)

	genesisHex := serializedHeaderHex(
		t, &chaincfg.SimNetParams.GenesisBlock.Header)
	headerHex, err := client.BlockHeader(0)
	require.NoError(t, err)
	require.Equal(t, genesisHex, headerHex)

	headerCount := int(bestHeight) + 1
	headers, err := client.BlockHeaders(0, headerCount)
	require.NoError(t, err)
	require.Equal(t, headerCount, headers.Count)
	require.Equal(t, 2016, headers.Max)
	require.Len(t, headers.Hex, headerCount*160)
	require.True(t, strings.HasPrefix(headers.Hex, genesisHex))
	require.True(t, strings.HasSuffix(headers.Hex, tip.Hex))

	var rpcErr *electrumclient.RPCError
	_, err = client.BlockHeader(-1)
	require.ErrorAs(t, err, &rpcErr)

	// A new block must be announced on the headers subscription.
	minedHashes, err := r.Client.Generate(1)
	require.NoError(t, err)

	headerNtfn := waitForHeaderTip(t, tipCh)
	require.Equal(t, bestHeight+1, headerNtfn.Height)
	minedHeader, err := r.Client.GetBlockHeader(minedHashes[0])
	require.NoError(t, err)
	require.Equal(t, serializedHeaderHex(t, minedHeader), headerNtfn.Hex)

	// The script hash methods, first while the script has no history at
	// all.
	addr, err := r.NewAddress()
	require.NoError(t, err)
	pkScript, err := txscript.PayToAddrScript(addr)
	require.NoError(t, err)
	scriptHash := electrumclient.ScriptHash(pkScript)

	status, statusCh, err := client.ScriptHashSubscribe(scriptHash)
	require.NoError(t, err)
	require.Nil(t, status, "expected a null status for a script hash "+
		"with no history")

	balance, err := client.ScriptHashGetBalance(scriptHash)
	require.NoError(t, err)
	require.Equal(t, &electrumclient.Balance{}, balance)

	history, err := client.ScriptHashGetHistory(scriptHash)
	require.NoError(t, err)
	require.Empty(t, history)

	mempoolHistory, err := client.ScriptHashGetMempool(scriptHash)
	require.NoError(t, err)
	require.Empty(t, mempoolHistory)

	unspents, err := client.ScriptHashListUnspent(scriptHash)
	require.NoError(t, err)
	require.Empty(t, unspents)

	// Pay to the script and check the mempool view of it. The transaction
	// only spends confirmed outputs so its history height is 0 and a
	// status notification for exactly that history must arrive.
	const sendAmt = btcutil.Amount(25_000_000)
	txHash, err := r.SendOutputs(
		[]*wire.TxOut{wire.NewTxOut(int64(sendAmt), pkScript)}, 10)
	require.NoError(t, err)

	mempoolItem := electrumclient.HistoryItem{
		Height: 0,
		TxHash: txHash.String(),
	}
	waitForStatus(t, statusCh, electrumclient.HistoryStatus(
		[]electrumclient.HistoryItem{mempoolItem}))

	mempoolHistory, err = client.ScriptHashGetMempool(scriptHash)
	require.NoError(t, err)
	require.Len(t, mempoolHistory, 1)
	require.Equal(t, txHash.String(), mempoolHistory[0].TxHash)
	require.Equal(t, int32(0), mempoolHistory[0].Height)
	require.Greater(t, mempoolHistory[0].Fee, int64(0))

	history, err = client.ScriptHashGetHistory(scriptHash)
	require.NoError(t, err)
	require.Equal(t, mempoolHistory, history)

	// The balance and unspent checks run as subtests so a failure in them
	// does not cut the coverage of everything after them short.
	t.Run("mempool balance and listunspent", func(t *testing.T) {
		balance, err = client.ScriptHashGetBalance(scriptHash)
		require.NoError(t, err)
		require.Equal(t, &electrumclient.Balance{
			Unconfirmed: int64(sendAmt),
		}, balance)

		unspents, err = client.ScriptHashListUnspent(scriptHash)
		require.NoError(t, err)
		require.Len(t, unspents, 1)
		require.Equal(t, txHash.String(), unspents[0].TxHash)
		require.Equal(t, int32(0), unspents[0].Height)
		require.Equal(t, int64(sendAmt), unspents[0].Value)
	})

	// Confirm the transaction and check that everything moves over to the
	// confirmed side.
	_, err = r.Client.Generate(1)
	require.NoError(t, err)
	_, confirmHeight, err := r.Client.GetBestBlock()
	require.NoError(t, err)

	confirmedItem := electrumclient.HistoryItem{
		Height: confirmHeight,
		TxHash: txHash.String(),
	}
	confirmedHistory := []electrumclient.HistoryItem{confirmedItem}
	waitForStatus(t, statusCh,
		electrumclient.HistoryStatus(confirmedHistory))

	history, err = client.ScriptHashGetHistory(scriptHash)
	require.NoError(t, err)
	require.Equal(t, confirmedHistory, history)

	mempoolHistory, err = client.ScriptHashGetMempool(scriptHash)
	require.NoError(t, err)
	require.Empty(t, mempoolHistory)

	t.Run("confirmed balance and listunspent", func(t *testing.T) {
		balance, err = client.ScriptHashGetBalance(scriptHash)
		require.NoError(t, err)
		require.Equal(t, &electrumclient.Balance{
			Confirmed: int64(sendAmt),
		}, balance)

		unspents, err = client.ScriptHashListUnspent(scriptHash)
		require.NoError(t, err)
		require.Len(t, unspents, 1)
		require.Equal(t, txHash.String(), unspents[0].TxHash)
		require.Equal(t, confirmHeight, unspents[0].Height)
		require.Equal(t, int64(sendAmt), unspents[0].Value)
	})

	wasSubscribed, err := client.ScriptHashUnsubscribe(scriptHash)
	require.NoError(t, err)
	require.True(t, wasSubscribed)

	_, chanOpen := <-statusCh
	require.False(t, chanOpen, "status channel must be closed after "+
		"unsubscribing")

	wasSubscribed, err = client.ScriptHashUnsubscribe(scriptHash)
	require.NoError(t, err)
	require.False(t, wasSubscribed)

	// The transaction methods, driven with the transaction confirmed
	// above.
	rawTxHex, err := client.TransactionGet(txHash.String())
	require.NoError(t, err)

	rpcTx, err := r.Client.GetRawTransaction(txHash)
	require.NoError(t, err)
	var rpcTxBuf bytes.Buffer
	require.NoError(t, rpcTx.MsgTx().Serialize(&rpcTxBuf))
	require.Equal(t, hex.EncodeToString(rpcTxBuf.Bytes()), rawTxHex)

	confirmHash, err := r.Client.GetBlockHash(int64(confirmHeight))
	require.NoError(t, err)
	confirmHeader, err := r.Client.GetBlockHeader(confirmHash)
	require.NoError(t, err)

	txMerkle, err := client.TransactionGetMerkle(
		txHash.String(), confirmHeight)
	require.NoError(t, err)
	require.Equal(t, confirmHeight, txMerkle.BlockHeight)
	verifyMerkleBranch(t, txHash, txMerkle.Merkle, txMerkle.Pos,
		&confirmHeader.MerkleRoot)

	posTxHash, err := client.TransactionIDFromPos(
		confirmHeight, txMerkle.Pos)
	require.NoError(t, err)
	require.Equal(t, txHash.String(), posTxHash)

	posResult, err := client.TransactionIDFromPosMerkle(
		confirmHeight, txMerkle.Pos)
	require.NoError(t, err)
	require.Equal(t, txHash.String(), posResult.TxHash)
	require.Equal(t, txMerkle.Merkle, posResult.Merkle)

	// Broadcasting a fresh transaction must land it in the node's mempool
	// and broadcasting it a second time must be rejected.
	broadcastAddr, err := r.NewAddress()
	require.NoError(t, err)
	broadcastScript, err := txscript.PayToAddrScript(broadcastAddr)
	require.NoError(t, err)

	broadcastTx, err := r.CreateTransaction(
		[]*wire.TxOut{wire.NewTxOut(int64(sendAmt), broadcastScript)},
		10, true)
	require.NoError(t, err)
	var broadcastBuf bytes.Buffer
	require.NoError(t, broadcastTx.Serialize(&broadcastBuf))

	broadcastHash, err := client.TransactionBroadcast(broadcastBuf.Bytes())
	require.NoError(t, err)
	require.Equal(t, broadcastTx.TxHash().String(), broadcastHash)

	// The server responds to the broadcast just before it inserts the
	// transaction into the mempool, so allow the node a moment to show it.
	broadcastTxHash := broadcastTx.TxHash()
	require.Eventually(t, func() bool {
		mempoolHashes, err := r.Client.GetRawMempool()
		require.NoError(t, err)
		for _, hash := range mempoolHashes {
			if *hash == broadcastTxHash {
				return true
			}
		}
		return false
	}, electrumNotificationTimeout, 100*time.Millisecond,
		"broadcast transaction never showed up in the mempool")

	_, err = client.TransactionBroadcast(broadcastBuf.Bytes())
	require.ErrorAs(t, err, &rpcErr)

	// The fee methods. The freshly started node has no fee data so the
	// estimate is either the no estimate marker or a real fee rate.
	estimate, err := client.EstimateFee(6)
	require.NoError(t, err)
	if estimate != -1 {
		require.Greater(t, estimate, 0.0)
	}

	relayFee, err := client.RelayFee()
	require.NoError(t, err)
	require.Equal(t, mempool.DefaultMinRelayTxFee.ToBTC(), relayFee)

	// The mempool holds just the small transaction broadcast above, far
	// below the size of the first histogram bin.
	histogram, err := client.MempoolGetFeeHistogram()
	require.NoError(t, err)
	require.Empty(t, histogram)

	// An unknown method must be answered with a method not found error.
	_, err = client.Call("bogus.method")
	require.ErrorAs(t, err, &rpcErr)
	require.Equal(t, int(btcjson.ErrRPCMethodNotFound.Code), rpcErr.Code)

	// The TLS listener must serve the electrum certificate pair, not the
	// RPC one.
	tlsConn, err := tls.Dial("tcp", tlsAddr,
		&tls.Config{InsecureSkipVerify: true})
	require.NoError(t, err)
	servedCert := tlsConn.ConnectionState().PeerCertificates[0].Raw
	require.NoError(t, tlsConn.Close())

	certPEM, err := os.ReadFile(node.certPath)
	require.NoError(t, err)
	certBlock, _ := pem.Decode(certPEM)
	require.NotNil(t, certBlock)
	require.Equal(t, certBlock.Bytes, servedCert)

	// The TLS listener must serve the same protocol.
	tlsClient, err := electrumclient.DialTLS(
		tlsAddr, &tls.Config{InsecureSkipVerify: true})
	require.NoError(t, err)
	t.Cleanup(tlsClient.Close)

	_, _, err = tlsClient.ServerVersion("btcd-integration-test", "1.4")
	require.NoError(t, err)
	require.NoError(t, tlsClient.Ping())
}

// TestElectrumServerBatchedRequests checks that requests sent as a JSON array
// are all answered.
func TestElectrumServerBatchedRequests(t *testing.T) {
	t.Parallel()

	tcpAddr := newElectrumNode(t, false, 0).tcpAddr

	conn, err := net.Dial("tcp", tcpAddr)
	require.NoError(t, err)
	t.Cleanup(func() { conn.Close() })
	require.NoError(t, conn.SetDeadline(
		time.Now().Add(electrumNotificationTimeout)))

	batch := `[{"jsonrpc":"2.0","id":1,"method":"server.ping","params":[]},` +
		`{"jsonrpc":"2.0","id":2,"method":"server.ping","params":[]}]` + "\n"
	_, err = conn.Write([]byte(batch))
	require.NoError(t, err)

	// Every request of the batch must be answered without an error. Accept
	// both response framings, one response object per line and a single
	// line holding an array of response objects.
	type response struct {
		ID    int64            `json:"id"`
		Error *json.RawMessage `json:"error"`
	}
	reader := bufio.NewReader(conn)
	responseIDs := make(map[int64]struct{})
	for len(responseIDs) < 2 {
		line, err := reader.ReadBytes('\n')
		require.NoError(t, err)

		var responses []response
		if err := json.Unmarshal(line, &responses); err != nil {
			var single response
			require.NoError(t, json.Unmarshal(line, &single),
				"unparseable response line: %s", line)
			responses = []response{single}
		}

		for _, resp := range responses {
			require.True(t, resp.Error == nil ||
				string(*resp.Error) == "null",
				"batched request errored: %s", line)
			responseIDs[resp.ID] = struct{}{}
		}
	}
	require.Len(t, responseIDs, 2)
}

// parseProtocolVersion turns a dotted protocol version like "1.4.2" into its
// numeric components.
func parseProtocolVersion(t *testing.T, version string) []int {
	t.Helper()

	parts := strings.Split(version, ".")
	numbers := make([]int, len(parts))
	for i, part := range parts {
		number, err := strconv.Atoi(part)
		require.NoError(t, err, "bad protocol version %q", version)
		numbers[i] = number
	}
	return numbers
}

// protocolVersionLEQ reports whether protocol version a is at most protocol
// version b, comparing the dotted components numerically with missing
// components counting as zero.
func protocolVersionLEQ(t *testing.T, a, b string) bool {
	t.Helper()

	aParts := parseProtocolVersion(t, a)
	bParts := parseProtocolVersion(t, b)
	for i := 0; i < len(aParts) || i < len(bParts); i++ {
		var aPart, bPart int
		if i < len(aParts) {
			aPart = aParts[i]
		}
		if i < len(bParts) {
			bPart = bParts[i]
		}
		if aPart != bPart {
			return aPart < bPart
		}
	}
	return true
}

// TestElectrumServerWireFormat drives the server over a raw connection and
// checks the exact JSON-RPC 2.0 shape of the bytes it sends, since wallet
// clients are strict about it. libnunchuk, the wallet library behind Nunchuk,
// fails any response that carries an "error" member even when it is null, and
// Electrum disconnects from a server whose negotiated protocol version falls
// outside the range the client requested. The shape checks are non fatal so
// one run reports every deviation at once.
func TestElectrumServerWireFormat(t *testing.T) {
	t.Parallel()

	wireNode := newElectrumNode(t, false, 0)
	r, tcpAddr := wireNode.Harness, wireNode.tcpAddr

	conn, err := net.Dial("tcp", tcpAddr)
	require.NoError(t, err)
	t.Cleanup(func() { conn.Close() })
	require.NoError(t, conn.SetDeadline(
		time.Now().Add(electrumNotificationTimeout)))

	reader := bufio.NewReader(conn)
	readMessage := func() map[string]json.RawMessage {
		t.Helper()

		line, err := reader.ReadBytes('\n')
		require.NoError(t, err)
		var fields map[string]json.RawMessage
		require.NoError(t, json.Unmarshal(line, &fields),
			"unparseable message: %s", line)
		return fields
	}
	send := func(req string) map[string]json.RawMessage {
		t.Helper()

		_, err := conn.Write([]byte(req + "\n"))
		require.NoError(t, err)
		return readMessage()
	}

	// A response to a successful request must carry the jsonrpc version,
	// the result, and the id of the request, and must not carry an error
	// member.
	fields := send(`{"jsonrpc":"2.0","id":7,"method":"server.ping","params":[]}`)
	assert.Equal(t, `"2.0"`, string(fields["jsonrpc"]))
	assert.Equal(t, `7`, string(fields["id"]))
	_, hasResult := fields["result"]
	assert.True(t, hasResult, "successful response is missing the result")
	_, hasError := fields["error"]
	assert.False(t, hasError, "successful response must not carry an "+
		"error member, not even a null one, since libnunchuk fails "+
		"every request that gets one back")

	// A response to a failed request must carry the error object and the
	// id of the request, and must not carry a result member.
	fields = send(`{"jsonrpc":"2.0","id":8,"method":"bogus.method","params":[]}`)
	assert.Equal(t, `8`, string(fields["id"]))
	errorJSON, hasError := fields["error"]
	require.True(t, hasError)
	require.NotEqual(t, "null", string(errorJSON))
	_, hasResult = fields["result"]
	assert.False(t, hasResult, "error response must not carry a "+
		"result member")

	// server.version takes the protocol range the client supports, sent
	// here exactly the way Nunchuk sends it, and the server must settle on
	// a version inside that range.
	fields = send(`{"jsonrpc":"2.0","id":9,"method":"server.version",` +
		`"params":["Nunchuk",["1.3","1.4.2"]]}`)
	var version []string
	require.NoError(t, json.Unmarshal(fields["result"], &version))
	require.Len(t, version, 2)
	assert.True(t, protocolVersionLEQ(t, "1.3", version[1]) &&
		protocolVersionLEQ(t, version[1], "1.4.2"),
		"negotiated protocol version %q is outside the requested "+
			"range of 1.3 through 1.4.2", version[1])

	// Subscription notifications are JSON-RPC notifications and must not
	// carry an id member, null or otherwise.
	fields = send(`{"jsonrpc":"2.0","id":10,"method":` +
		`"blockchain.headers.subscribe","params":[]}`)
	assert.Equal(t, `10`, string(fields["id"]))

	_, err = r.Client.Generate(1)
	require.NoError(t, err)

	fields = readMessage()
	require.Equal(t, `"blockchain.headers.subscribe"`,
		string(fields["method"]))
	var params []json.RawMessage
	require.NoError(t, json.Unmarshal(fields["params"], &params))
	require.Len(t, params, 1)
	_, hasID := fields["id"]
	assert.False(t, hasID, "notifications must not carry an id member")
}
